// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5gDRNrgjQxoeYz1bsVPJqMJVn00sSdTc',
    appId: '1:1010188362147:web:a59f62bfb40f24ad753a16',
    messagingSenderId: '1010188362147',
    projectId: 'sportguard-ai-7a73a',
    authDomain: 'sportguard-ai-7a73a.firebaseapp.com',
    databaseURL: 'https://sportguard-ai-7a73a-default-rtdb.firebaseio.com',
    storageBucket: 'sportguard-ai-7a73a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXfOaC2pYUZkzOhZv-8t8xapAfLYpCInY',
    appId: '1:1010188362147:android:fe5b404094074f90753a16',
    messagingSenderId: '1010188362147',
    projectId: 'sportguard-ai-7a73a',
    databaseURL: 'https://sportguard-ai-7a73a-default-rtdb.firebaseio.com',
    storageBucket: 'sportguard-ai-7a73a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMYziD75fLGRGkkOOSqBoRXuvx-6UkHJk',
    appId: '1:1010188362147:ios:c280f37214358710753a16',
    messagingSenderId: '1010188362147',
    projectId: 'sportguard-ai-7a73a',
    databaseURL: 'https://sportguard-ai-7a73a-default-rtdb.firebaseio.com',
    storageBucket: 'sportguard-ai-7a73a.firebasestorage.app',
    iosBundleId: 'com.example.flutterAp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMYziD75fLGRGkkOOSqBoRXuvx-6UkHJk',
    appId: '1:1010188362147:ios:c280f37214358710753a16',
    messagingSenderId: '1010188362147',
    projectId: 'sportguard-ai-7a73a',
    databaseURL: 'https://sportguard-ai-7a73a-default-rtdb.firebaseio.com',
    storageBucket: 'sportguard-ai-7a73a.firebasestorage.app',
    iosBundleId: 'com.example.flutterAp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5gDRNrgjQxoeYz1bsVPJqMJVn00sSdTc',
    appId: '1:1010188362147:web:bde9bef67b0c060f753a16',
    messagingSenderId: '1010188362147',
    projectId: 'sportguard-ai-7a73a',
    authDomain: 'sportguard-ai-7a73a.firebaseapp.com',
    databaseURL: 'https://sportguard-ai-7a73a-default-rtdb.firebaseio.com',
    storageBucket: 'sportguard-ai-7a73a.firebasestorage.app',
  );
}
